server:
  port: 7000
spring:
  application:
    name: eureka-server1
eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka服务中,本身就是所有无需注册
    fetch-registry: false #是否从Eureka中获取注册信息
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    hostname: localhost
    #每隔多久发送一次心跳
    lease-renewal-interval-in-seconds: 20
    #每隔多久检查一次心跳
    lease-expiration-duration-in-seconds: 120
  #出于保护自己开启自我保护
  server:
    enable-self-preservation: false