server:
  port: 9005
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        get:
          uri: https://github.com/14s25s36s/javastudy.git
          search-paths: /demo-config-server/src/main/resources/
          username: 14s25s36s
          password: aa700824.